"""'initial'

Revision ID: c16e396427bf
Revises: 
Create Date: 2023-01-30 21:51:26.338084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c16e396427bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curr_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('buy_value', sa.Float(), nullable=True),
    sa.Column('sell_value', sa.Float(), nullable=True),
    sa.Column('date_add', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curr_history')
    op.drop_table('Users')
    # ### end Alembic commands ###
